[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = default.csv
build_flags =
    -I .pio/libdeps/$PIOENV/berry/default
    -I .pio/libdeps/$PIOENV/berry/generate
lib_ldf_mode = deep+
lib_archive = no
lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0
    adafruit/DHT sensor library @ ^1.4.0
    adafruit/Adafruit Unified Sensor @ ^1.1.0
    https://github.com/berry-lang/berry.git
